ODYA-262 대표여행일지 응답 값 수정
weIT-1st/Odya-server pull request #97
Opened 2024-01-14 09:27 UTC by yeongchan1228

### 개요
- 여행일지 응답에 대표여행일지 여부를 알 수 있어야 한다.
- 대표여행일지 응답에 콘텐츠 내용이 포함되어야 한다.
### 변경사항
- 여행일지, 대표여행일지, 여행일지북마크 응답값에 대표여행일지여부, 북마크여부, 콘텐츠 필드 추가
### 관련 지라 및 위키 링크
- [ODYA-262](https://weit.atlassian.net/browse/ODYA-262)
### 리뷰어에게 하고 싶은 말
- 지혜님 제보로 수정했습니다!!

2024-01-14 10:04 UTC, konempty approved these changes
고생하셧습니다 👍 👍

2024-01-14 13:39 UTC, lin-chae approved these changes
고생하셨습니다 👍

2024-01-15 05:25 UTC, konempty requested changes
<img width="807" alt="스크린샷 2024-01-15 오후 2 24 37" src="https://github.com/weIT-1st/Odya-server/assets/44064530/45db78a2-0567-4600-9fb8-e8ef0ab04c64">

 fileService.getPreAuthenticatedObjectUrl(travelCompanion.user.profile.profileName),

희오님이 제보주신 문제는
요렇게 되어야 겠네요..!

2024-01-15 05:28 UTC, konempty approved these changes
희오님 이슈만 처리하고 바로 머지해도 좋을것 같습니다~!

2024-01-15 13:32 UTC, merged